services:
  - type: web
    name: alphaadvisor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT application:application
    envVars:
      - key: FRONTEND_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
        generateValue: false
      - key: PORT
        value: 8000



