branch-defaults:
  default:
    environment: alphaadvisor-env
    group_suffix: null
  master:
    environment: Alphaadvisor-v4-env
global:
  application_name: alphaadvisor-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application

